### ISSUE TITLE
UnicodeEncodeError while creating a zip

### ISSUE THREAD

**Issue by rgaudin** [openzim/librechef#1]
Ran the chef and it failed on a connection error. There are apparently errors in retry mechanism – or at least in its logging– making it difficult to diagnose.
I suppose the encoding and zip issues are just due to the lack of data from that network error. Should ideally fail directlt instead.

```
INFO     --------- Chapter: 4: Objects and Arrays
INFO     ---------   url: https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Eloquent_JavaScript_(Haverbeke)/Part_1%3A_Language/04%3A_Objects_and_Arrays
INFO     ----- Course Index title: 5: Higher-order Functions
INFO     -----    url: https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Eloquent_JavaScript_(Haverbeke)/Part_1%3A_Language/05%3A_Higher-order_Functions
INFO     --------- Chapter: 5: Higher-order Functions
INFO     ---------   url: https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Eloquent_JavaScript_(Haverbeke)/Part_1%3A_Language/05%3A_Higher-order_Functions
Error with connection ('('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'); about to perform retry 1 of 5.
Error with connection ('('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'); about to perform retry 1 of 5.
Error with connection ('('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'); about to perform retry 1 of 5.
Traceback (most recent call last):
  File "./sushichef.py", line 593, in write_index
    zipper.write_index_contents(content)
  File "/usr/local/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 115, in write_index_contents
    self._write_to_zipfile('index.html', contents)
  File "/usr/local/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 34, in _write_to_zipfile
    self.zf.writestr(info, content)
  File "/usr/local/lib/python3.8/zipfile.py", line 1786, in writestr
    data = data.encode("utf-8")
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 22299-22302: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sushichef.py", line 1412, in <module>
    chef.main()
  File "/usr/local/lib/python3.8/site-packages/ricecooker/chefs.py", line 289, in main
    self.run(args, options)
  File "/usr/local/lib/python3.8/site-packages/ricecooker/chefs.py", line 279, in run
    self.pre_run(args, options)
  File "./sushichef.py", line 1308, in pre_run
    channel_tree = self.scrape(args, options)
  File "./sushichef.py", line 1388, in scrape
    for collection_node in collections.to_node():
  File "./sushichef.py", line 157, in to_node
    yield collection.to_node()
  File "./sushichef.py", line 190, in to_node
    topic.units()
  File "./sushichef.py", line 269, in units
    course_index.index(build_path(base_path + [chapter_link.text]))
  File "./sushichef.py", line 484, in index
    result = course_index.index(
  File "./sushichef.py", line 484, in index
    result = course_index.index(
  File "./sushichef.py", line 491, in index
    chapter.to_file(chapter_basepath)
  File "./sushichef.py", line 852, in to_file
    self.write_index(
  File "./sushichef.py", line 593, in write_index
    zipper.write_index_contents(content)
  File "/usr/local/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 26, in __exit__
    self.close()
  File "/usr/local/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 58, in close
    raise ReferenceError("Invalid Zip at {}: missing index.html file (use write_index_contents method)".format(self.write_to_path))
ReferenceError: Invalid Zip at chefdata/eng/Bookshelves/Computer Science/Book: Eloquent JavaScript (Haverbeke)/Part 1: Language/5: Higher-order Functions/5: Higher-order Functions.zip: missing index.html file (use write_index_contents method)
INFO     Deleting chef temp files at /app/.ricecooker-temp
```

**Comment by satyamtg** [comment]
Tried on my local machine. Doesn't seem to be a connection issue. The run failed at that very specific book with the following -
```
_Language/05%3A_Higher-order_Functions
INFO     --------- Chapter: 5: Higher-order Functions
INFO     ---------   url: https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Eloquent_JavaScript_(Haverbeke)/Part_1%3A_Language/05%3A_Higher-order_Functions
Traceback (most recent call last):
  File "sushichef.py", line 593, in write_index
    zipper.write_index_contents(content)
  File "/home/satyamtg/Projects/sushi/venv/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 115, in write_index_contents
    self._write_to_zipfile('index.html', contents)
  File "/home/satyamtg/Projects/sushi/venv/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 34, in _write_to_zipfile
    self.zf.writestr(info, content)
  File "/usr/lib/python3.8/zipfile.py", line 1786, in writestr
    data = data.encode("utf-8")
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 22299-22302: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sushichef.py", line 1412, in <module>
    chef.main()
  File "/home/satyamtg/Projects/sushi/venv/lib/python3.8/site-packages/ricecooker/chefs.py", line 289, in main
    self.run(args, options)
  File "/home/satyamtg/Projects/sushi/venv/lib/python3.8/site-packages/ricecooker/chefs.py", line 279, in run
    self.pre_run(args, options)
  File "sushichef.py", line 1308, in pre_run
    channel_tree = self.scrape(args, options)
  File "sushichef.py", line 1388, in scrape
    for collection_node in collections.to_node():
  File "sushichef.py", line 157, in to_node
    yield collection.to_node()
  File "sushichef.py", line 190, in to_node
    topic.units()
  File "sushichef.py", line 269, in units
    course_index.index(build_path(base_path + [chapter_link.text]))
  File "sushichef.py", line 484, in index
    result = course_index.index(
  File "sushichef.py", line 484, in index
    result = course_index.index(
  File "sushichef.py", line 491, in index
    chapter.to_file(chapter_basepath)
  File "sushichef.py", line 852, in to_file
    self.write_index(
  File "sushichef.py", line 593, in write_index
    zipper.write_index_contents(content)
  File "/home/satyamtg/Projects/sushi/venv/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 26, in __exit__
    self.close()
  File "/home/satyamtg/Projects/sushi/venv/lib/python3.8/site-packages/ricecooker/utils/html_writer.py", line 58, in close
    raise ReferenceError("Invalid Zip at {}: missing index.html file (use write_index_contents method)".format(self.write_to_path))
ReferenceError: Invalid Zip at chefdata/eng/Bookshelves/Computer Science/Book: Eloquent JavaScript (Haverbeke)/Part 1: Language/5: Higher-order Functions/5: Higher-order Functions.zip: missing index.html file (use write_index_contents method)
INFO     Deleting chef temp files at /home/satyamtg/Projects/sushi/.ricecooker-temp
```

The connection error might have been resolved once ricecooker performed the retry step. It looks like the error is actually while writing the zip file.

Also, this happens with ricecooker and not with the sushi-chef. I'm trying to re-download the file that created this error.

**Comment by satyamtg** [comment]
I think this can be closed

**Comment by rgaudin** [comment]
Agrees
